### ISSUE TITLE
需要一个完整展示clojure开发流程的演讲。

### ISSUE THREAD

**Issue by qiuxiafei** [acug/drinkup#3]
包括：
- 项目目录结构
- lein使用
- 测试
- 调试
- 打包
- 发布
- 项目中的常见需求：log，配置等等

**Comment by pfmiles** [comment]
呵呵..这个估计只有“外聘讲师”了

2013/4/27 Xiafei Qiu notifications@github.com

> 包括：
> - 项目目录结构
> - lein使用
> - 测试
> - 调试
> - 打包
> - 发布
> - 项目中的常见需求：log，配置等等
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/acug/drinkup/issues/3
> .

## 

Regards.
Yue . Wen

**Comment by qiuxiafei** [comment]
@pfmiles 也不一定啊，不在乎项目大小，完完整整走过全过程的就好。

**Comment by weejulius** [comment]
大家有什么想了解尽量多地在这里列出来吧
