### ISSUE TITLE
DrinkUp NO.0

### ISSUE THREAD

**Issue by pfmiles** [acug/drinkup#8]
举办第一次"drink up"...  
议题分享：  
1. STM简介与源代码分析  (@xumingming)
2. monads  (@xperian)
3. clojure开发流程展示  (@weejulius)

**Comment by pfmiles** [comment]
相关议题准备好后请在群里吼；
群里吼出具体召开地点；
群里后续会吼出具体召开时间

**Comment by qiuxiafei** [comment]
关于地点的投票：https://docs.google.com/forms/d/1Aj5pf8tXkp_DRIPj60Gh6fvouuIEd3_l5OPB-5_HGSQ/viewform

**Comment by qiuxiafei** [comment]
成功举行~~~
